### ISSUE TITLE
taskset: failed to set pid affinity

### ISSUE THREAD

**Issue by abiswal2001** [sc2682cornell/PARTIES#1]
When running the client ./run.sh script having started the memcached server with mutated set up, I encounter the error message:

`taskset: failed to set pid 3789's affinity: Invalid argument`

For context, I am running the script with the following arguments:
`./run.sh 4 10 4000000 200 2500 2 127.0.0.1 11211`

**Comment by sc2682cornell** [comment]
You'll need to double check the arguments in taskset.
